### ISSUE TITLE
如何阅读gitbook

### ISSUE THREAD

**Issue by wolfdan666** [talkgo/read#31]
就像go圣经的如下链接
https://www.gitbook.com/book/wizardforcel/gopl-zh/details

会自动跳转gitbook首页，登录了也没用

**Comment by wayland3** [comment]
您好！您的邮件已收到，谢谢！

**Comment by yangwenmai** [comment]
@wolfdan666 我已经替换新的链接，现在可以在线阅读了。

谢谢你的反馈。

**Comment by wayland3** [comment]
您好！您的邮件已收到，谢谢！

**Comment by wtfstring** [comment]
您好！邮件已收到！我会尽快回复！！
